// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// Pi owns the RPC semantics and implementation. This version-pinned boundary
// schema owns every JSONL field Charly accepts or emits while delegating those
// messages unchanged to upstream runRpcMode.
type PiPlugin struct {
	Runtime string `yaml:"runtime,omitempty" json:"runtime"`

	Contract string `yaml:"contract,omitempty" json:"contract"`
}

type PiRPCCommand struct {
	Id string `yaml:"id,omitempty" json:"id,omitempty"`

	Type string `yaml:"type,omitempty" json:"type"`

	Message string `yaml:"message,omitempty" json:"message,omitempty"`

	Images []any/* CUE top */ `yaml:"images,omitempty" json:"images,omitempty"`

	StreamingBehavior string `yaml:"streamingBehavior,omitempty" json:"streamingBehavior,omitempty"`

	ParentSession string `yaml:"parentSession,omitempty" json:"parentSession,omitempty"`

	Provider string `yaml:"provider,omitempty" json:"provider,omitempty"`

	ModelId string `yaml:"modelId,omitempty" json:"modelId,omitempty"`

	Level string `yaml:"level,omitempty" json:"level,omitempty"`

	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`

	CustomInstructions string `yaml:"customInstructions,omitempty" json:"customInstructions,omitempty"`

	Enabled bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`

	Command string `yaml:"command,omitempty" json:"command,omitempty"`

	ExcludeFromContext bool `yaml:"excludeFromContext,omitempty" json:"excludeFromContext,omitempty"`

	OutputPath string `yaml:"outputPath,omitempty" json:"outputPath,omitempty"`

	SessionPath string `yaml:"sessionPath,omitempty" json:"sessionPath,omitempty"`

	EntryId string `yaml:"entryId,omitempty" json:"entryId,omitempty"`

	Since string `yaml:"since,omitempty" json:"since,omitempty"`

	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	Value string `yaml:"value,omitempty" json:"value,omitempty"`

	Confirmed bool `yaml:"confirmed,omitempty" json:"confirmed,omitempty"`

	Cancelled bool `yaml:"cancelled,omitempty" json:"cancelled,omitempty"`
}

type PiGetStateCommand struct {
	Id string `yaml:"id,omitempty" json:"id"`

	Type string `yaml:"type,omitempty" json:"type"`
}

type PiPromptCommand struct {
	Id string `yaml:"id,omitempty" json:"id"`

	Type string `yaml:"type,omitempty" json:"type"`

	Message string `yaml:"message,omitempty" json:"message"`
}

type PiAbortCommand struct {
	Type string `yaml:"type,omitempty" json:"type"`
}

// Events are passed through losslessly. The discriminator and the response
// fields Charly interprets are closed and typed; event-specific upstream data
// remains opaque to the adapter.
type PiRPCEvent map[string]any /* CUE top */

type PiRPCState struct {
	Model any/* CUE top */ `yaml:"model,omitempty" json:"model,omitempty"`

	ThinkingLevel string `yaml:"thinkingLevel,omitempty" json:"thinkingLevel"`

	IsStreaming bool `yaml:"isStreaming,omitempty" json:"isStreaming"`

	IsCompacting bool `yaml:"isCompacting,omitempty" json:"isCompacting"`

	SteeringMode string `yaml:"steeringMode,omitempty" json:"steeringMode"`

	FollowUpMode string `yaml:"followUpMode,omitempty" json:"followUpMode"`

	SessionFile string `yaml:"sessionFile,omitempty" json:"sessionFile,omitempty"`

	SessionId string `yaml:"sessionId,omitempty" json:"sessionId"`

	SessionName string `yaml:"sessionName,omitempty" json:"sessionName,omitempty"`

	AutoCompactionEnabled bool `yaml:"autoCompactionEnabled,omitempty" json:"autoCompactionEnabled"`

	MessageCount int64 `yaml:"messageCount,omitempty" json:"messageCount"`

	PendingMessageCount int64 `yaml:"pendingMessageCount,omitempty" json:"pendingMessageCount"`
}

type PiRPCStateResponse struct {
	Id string `yaml:"id,omitempty" json:"id,omitempty"`

	Type string `yaml:"type,omitempty" json:"type"`

	Command string `yaml:"command,omitempty" json:"command"`

	Success bool `yaml:"success,omitempty" json:"success"`

	Data *PiRPCState `yaml:"data,omitempty" json:"data,omitempty"`

	Error string `yaml:"error,omitempty" json:"error,omitempty"`
}
